### ISSUE TITLE
[question] a matrix calculating question

### ISSUE THREAD

**Issue by qwq321qwq** [mahaarbo/urdf2casadi#12]
I have a question about this program.
In urdf2casadi/examples/user/ur5_example.ipynb, the dynamic parameters are written as To obtain the dynamic parameters (M, C, G) of the equation of motion tau = M(q)q_ddot + C(q, q_dot)q_dot + G(q). But the example shows  C(q, q_dot) is a 6*1 matrix and wo know q_dot is a 6*1 matrix. So how does it work?
Thanks for your answers! orz @mahaarbo @lillmaria

**Comment by mahaarbo** [comment]
Hi, sorry for the late reply. The `get_coriolis_rnea` function actually produces the Coriolis bias vector, not the Coriolis matrix. I will update the example with the proper descriptions of how the dynamic parameters are obtained shortly.

**Comment by mahaarbo** [comment]
Hope the description is a little easier to follow now.
