### ISSUE TITLE
Load xacro instead of urdf

### ISSUE THREAD

**Issue by kunpengyao** [mahaarbo/urdf2casadi#13]
Hello, is it possible to load xacro file directly to the parser without manually converting the file format? Thanks.

**Comment by mahaarbo** [comment]
Hi, the python library uses `urdf_parser_py` to parse the URDF, and it can therefore not load xacro files directly. Xacro files can easily be converted to URDF with the command `xacro` if you have ROS installed on your system. So one way you can do it in your scripts is to call xacro from python and use the output with urdf2casadi.
