### ISSUE TITLE
Publishing to pypi?

### ISSUE THREAD

**Issue by maxspahn** [mahaarbo/urdf2casadi#16]
Hi,

do you plan on publishing urdf2casadi to the Python Package Index (www.pypi.org)?
That would be great, because currently, it is not possible to use it as a dependency in other pypi packages.

**Comment by mahaarbo** [comment]
Hi,

Good idea!
I can look into it when I get back in the office after the holidays.

**Comment by mahaarbo** [comment]
Finally got around to [publishing the package to PyPi](https://pypi.org/project/urdf2casadi/).

Please have a look and see if it works as desired.

**Comment by maxspahn** [comment]
Nice. I worked on your package as well today.
I worked on it as well. I added poetry as a possible package manager. This allows you to very much simplify pushing to pypi.
You can have a look at it within the next hour.

**Comment by mahaarbo** [comment]
Was this the PR? https://github.com/mahaarbo/urdf2casadi/pull/17

**Comment by maxspahn** [comment]
Yeah, but for some reason the workflow does not work anymore. So, I'll fix it before reopening the PR again.

**Comment by mahaarbo** [comment]
I've published the new package to PyPi: [pypi/1.2.0](https://pypi.org/project/urdf2casadi/1.2.0/), but somehow the poetry built version didn't include the Readme. Do you have any experience with poetry and pypi?

**Comment by maxspahn** [comment]
I have added a pull request to fix that (and some other minor poetry-related issues)
Essentially, you have to specify the readme in the `pyproject.toml` file.
