### ISSUE TITLE
installation not working

### ISSUE THREAD

**Issue by Ukias** [mahaarbo/urdf2casadi#26]
Installation on Linux Ubuntu without Ros. I tried with poetry as well as with pip.

command conda list yields:
urdf2casadi               0.2.0                    pypi_0    pypi

When I run a casclik example script, I get:

ImportError: cannot import name 'converter' from 'urdf2casadi' (/home/account/.local/lib/python3.7/site-packages/urdf2casadi/init.py)

**Comment by mahaarbo** [comment]
Sorry for the late reply, `casclik` is quite old and uses the earlier version of `urdf2casadi` where I had only implemented forward kinematics functions. I'd recommend looking into other frameworks that achieve similar things but are much more thoroughly developed such as [jrl-umi3218/Tasks](https://github.com/jrl-umi3218/Tasks) or [eTaSL](https://etasl.pages.gitlab.kuleuven.be/).

**Comment by Ukias** [comment]
Thanks
