### ISSUE TITLE
Conversion for Floating Base Systems

### ISSUE THREAD

**Issue by emrecemal** [mahaarbo/urdf2casadi#31]
Hello, 

I was wondering if the URDF to CasADi conversion works for floating base systems like mobile robots?

**Comment by mahaarbo** [comment]
The current implementation hasn't really dealt with floating base systems, but everything in this library is based on "Rigid Body Dynamics Algorithms" by Roy Featherstone (2008), so it should be possible. 
If you look into it, I'd be more than happy to review and accept pull requests.
