### ISSUE TITLE
The geometry is not properly installed

### ISSUE THREAD

**Issue by DentOpt** [mahaarbo/urdf2casadi#4]
Hi, 
`ModuleNotFoundError: No module named 'geometry'`

I tried both installation instructions. 
However as a result, I always get from 
`from urdf2casadi import urdfparser as u2c`
the error:
`ModuleNotFoundError: No module named 'geometry'`
Is there some additional installing necessary of a geometry package? - I have ros geomety and geometry2 packages installed

Thanks

**Comment by mahaarbo** [comment]
Hi, geometry is a local python module. The problem was probably the way that I had done imports. 
Try it with the latest changes and see if that works.
