### ISSUE TITLE
Cannot load shared library libcasadi_importer_clang 

### ISSUE THREAD

**Issue by Leo-Simpson** [mahaarbo/urdf2casadi#5]
Hi, I am trying to use urdf2casadi on macOS, but cannot run `get_forward_kinematics()` for example, because of [this issue](https://github.com/casadi/casadi/issues/1941). (that you opened btw !)

For me the problem was fixed by doing exactly what was mentioned in the issue (i.e. adding `"compiler": "shell"` to the opts dict line 16 and 589 of `urdfparser.py ` ). Even if the problem is fixed for me, I thought this remark could be useful.

**Comment by mahaarbo** [comment]
Thanks! I've added a platform check to modify the compiler option, can you check if it works? I don't have a mac available at the moment.

**Comment by Leo-Simpson** [comment]
Yes it worked ! Thank you !
